### ISSUE TITLE
Problems with "_ALS" error using 2.11.4

### ISSUE THREAD

**Issue by marcoguzman0** [Y-Less/sscanf#42] opened 2022-04-18 19:41 UTC
Hi there! I have some errors after compile my gamemode using sscanf 2.11.4

`
C:\Users\marco\Desktop\Server RP\ServerRP.pwn:99 (error) undefined symbol "_ALS"; did you mean "ALL"?
C:\Users\marco\Desktop\Server RP\ServerRP.pwn:99 (error) invalid expression, assumed zero
C:\Users\marco\Desktop\Server RP\ServerRP.pwn:99 (error) undefined symbol "_ALS_go"
C:\Users\marco\Desktop\Server RP\ServerRP.pwn:99 (fatal) too many error messages on one line
Build encountered fatal error
`

The code in the gamemode is this...

`
public OnGameModeExit()
{
	for (new i = 0, j = GetPlayerPoolSize(); i <= j; i++) 
	{
		if (IsPlayerConnected(i))
		{
			OnPlayerDisconnect(i, 1); // This is the line 99
		}
	}
	mysql_close(g_SQL);
	return 1;
}
`

What should I do to fix it?
I apologize for my poor English :s

**Comment by daniscript18** [comment] 2023-07-10 21:39
I'm new to sscanf, honestly it's the first time I've used it so I had the same problem. No more responding in case someone also had the same problem. It can be fixed by using `SSCANF_OnPlayerDisconnect()` instead of `OnPlayerDisconnect()`.

I don't know what the problem is, maybe it's a newbie problem, I use all my updated plugins/includes, also the compiler so I doubt it's because I don't have something updated, I even use the windows libraries in their new versions .

```pawn
public OnGameModeExit() {
    for(new i = 0, j = GetPlayerPoolSize(); i <= j; i++)  {
        if(IsPlayerConnected(i)) {
            SSCANF_OnPlayerDisconnect(i, 1);
        }
    }
    mysql_close(g_SQL);
    return true;
}
```

**Comment by Y-Less** [comment] 2023-09-08 20:25
So the problem is calling callbacks directly.  Don't.

**Closed as completed by Y-Less** 2023-09-08 20:25 UTC
